<?php

use App\Story;
use Illuminate\Database\Seeder;

class StoryFactory extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Story::insert([
            [
                'user_id' => '1',
                'tag_id' => '1',
                'slug' => 'The-Spark-of-Inspiration-Igniting-the-Fire-Within-u-admin',
                'title' => 'The Spark of Inspiration: Igniting the Fire Within',
                'body' => '<p>In a small town filled with dreamers, there lived a young artist named Maya. Despite her undeniable talent, Maya found herself in the grip of a creative block, feeling uninspired and lost. Determined to reignite her passion, she embarked on a quest to seek inspiration.</p><p>Her journey took her to various places, from bustling city streets to serene natural landscapes. Along the way, she encountered a diverse group of individuals who shared their stories of triumph, perseverance, and resilience. Each person had faced their own challenges but had managed to overcome them through unwavering determination and a relentless pursuit of their dreams.</p><p>One encounter was with an elderly sculptor named Mr. Johnson, who had spent decades perfecting his craft. He imparted wisdom about the importance of embracing failure and learning from mistakes. His story reminded Maya that setbacks were not roadblocks but stepping stones on the path to success.</p><p>In another instance, Maya stumbled upon a vibrant community center where children from different backgrounds gathered to express themselves through art. Their uninhibited creativity and boundless imagination served as a powerful reminder that inspiration could be found in even the simplest of moments.</p><p>Throughout her journey, Maya discovered that inspiration was not a fleeting muse but a state of mind that could be cultivated. She learned to find beauty in the mundane, draw strength from her own vulnerabilities, and appreciate the unique perspectives of others.</p><p>Armed with newfound inspiration, Maya returned to her art studio with a renewed sense of purpose. She poured her heart and soul into her work, infusing each piece with the stories she had gathered and the experiences she had encountered. Maya\'s art became a source of inspiration for others, igniting their own creative sparks and reminding them of the power of pursuing their passions.</p><p>"The Spark of Inspiration: Igniting the Fire Within" is a story that celebrates the transformative power of inspiration. It reminds us that inspiration can be found in the most unexpected places, and that by embracing it, we can unlock our full potential and create meaningful impact in the world.</p>',
                'readtime' => '1 Minute 54 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '2',
                'slug' => 'The-Gift-of-Connection-A-Heartwarming-Encounter-u-admin',
                'title' => 'The Gift of Connection: A Heartwarming Encounter',
                'body' => '<p>In a bustling city, amidst the fast pace of life, an unexpected encounter unfolded that would warm the hearts of all involved. Emma, a young professional on her daily commute, noticed an elderly gentleman named Mr. Wilson sitting alone on a bench, looking a bit lost and disheartened.</p><p>Driven by compassion, Emma approached Mr. Wilson and struck up a conversation. She discovered that he had recently lost his wife, and the loneliness had begun to weigh heavily on him. Emma\'s empathetic nature compelled her to reach out, offering a listening ear and a shoulder to lean on.</p><p>As they continued talking, Mr. Wilson shared stories of his life with his beloved wife, their adventures, and the memories they had cherished. Emma, touched by his profound love and the depth of his grief, felt a deep sense of connection with him. She realized that sometimes, a simple act of kindness and genuine companionship could make a world of difference in someone\'s life.</p><p>In the following days, Emma and Mr. Wilson formed an unlikely friendship. They spent time together, sharing meals, going for walks in the park, and engaging in heartfelt conversations. Emma\'s presence brought comfort and joy to Mr. Wilson, while he imparted invaluable life lessons and wisdom to her.</p><p>Word of their heartwarming bond spread throughout the community, inspiring others to reach out and connect with those around them. Acts of kindness began to ripple through the city, and strangers became friends, fostering a sense of unity and compassion.</p><p>As time passed, Mr. Wilson\'s spirits lifted, and he rediscovered the joys of life. Emma, too, found a deeper purpose in her interactions with others, realizing the transformative power of genuine human connection.</p><p>"The Gift of Connection: A Heartwarming Encounter" is a tale that reminds us of the immense impact small acts of kindness can have. It illustrates the profound beauty of forging connections with strangers, and how these connections can bring solace, happiness, and a renewed sense of purpose. Through Emma and Mr. Wilson\'s journey, we learn that genuine compassion has the power to mend hearts, uplift spirits, and create a world filled with warmth and love.</p>',
                'readtime' => '1 Minute 57 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '3',
                'slug' => 'Courage-Unveiled-Embracing-Bravery-in-the-Face-of-Adversity-u-admin',
                'title' => 'Courage Unveiled: Embracing Bravery in the Face of Adversity',
                'body' => '<p>In a quaint village nestled at the foot of a towering mountain, there lived a young woman named Lily. She was known for her gentle spirit and kind heart. However, deep within her, there was a yearning for something more—a desire to conquer her fears and step into a world of endless possibilities.</p><p>One day, Lily stumbled upon an old journal left behind by her late grandmother, who was renowned for her unwavering courage. Intrigued by the stories of adventure and resilience within its pages, Lily embarked on a personal quest to discover her own courage.</p><p>Her journey took her through treacherous terrains, both physical and emotional. She scaled steep cliffs, faced daunting challenges, and encountered moments of self-doubt. But with each hurdle, she found a hidden reserve of strength she never knew existed.her quest.</p><p>As Lily continued her voyage, she encountered fellow travelers who were also seeking their own courage. They formed a support network, encouraging and uplifting one another during moments of doubt. Through their shared experiences and collective strength, they discovered that courage could be nurtured and grown.</p><p>In a triumphant moment of self-discovery, Lily reached the mountaintop, both literally and metaphorically. From this vantage point, she gained a newfound perspective on life—a realization that the greatest adventures and transformations occur when one embraces their fears and takes a leap of faith.</p><p>Returning to her village, Lily became a beacon of courage and inspiration for others. She shared her stories, encouraging those around her to step outside their comfort zones and embrace the unknown. Her acts of bravery ignited a spark in the hearts of many, fostering a community built on resilience and fearless pursuit of dreams.uncover the extraordinary possibilities that await us on the other side of fear.</p>',
                'readtime' => '2 Minute 15 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '4',
                'slug' => 'The-Ripple-of-Appreciation:-Gratitude-Enduring-Impact-u-admin',
                'title' => 'The Ripple of Appreciation: Gratitude\'s Enduring Impact',
                'body' => '<p>In a bustling city filled with people rushing through their daily lives, a remarkable story of appreciation unfolded. Emily, a young professional with a hectic schedule, found herself caught up in the never-ending cycle of tasks and responsibilities. However, a serendipitous encounter would remind her of the power of appreciation.</p><p>One evening, on her way home from work, Emily noticed an elderly man named Mr. Thompson sitting on a park bench, sketching the vibrant sunset before him. Intrigued by his passion and talent, she struck up a conversation. As they talked, she learned that Mr. Thompson had spent a lifetime capturing the beauty of the world through his artwork.</p><p>Intrigued and moved by his dedication, Emily expressed her genuine appreciation for his talent and the joy his creations brought to others. Mr. Thompson, humbled by her words, shared his belief in the transformative power of appreciation. He spoke of the ripple effect it could create, spreading kindness and positivity throughout society.</p><p>Inspired by their conversation, Emily embarked on a personal mission to express appreciation to those around her. She wrote heartfelt letters to her loved ones, acknowledging their support and the impact they had on her life. She took the time to notice and compliment the barista who made her morning coffee and expressed gratitude to the janitor who kept her workplace clean.</p><p>As Emily continued to appreciate others, she witnessed the profound impact her words had on their lives. The barista beamed with joy, energized by the recognition of her hard work. The janitor\'s face lit up with surprise and appreciation, feeling seen and valued for his often-overlooked efforts.</p><p>Word of Emily\'s acts of appreciation spread throughout the city, inspiring others to follow suit. The simple act of expressing gratitude became contagious, fostering a culture of appreciation within the community. People began to notice and acknowledge the contributions of others, creating an atmosphere of positivity and interconnectedness.</p><p>Through her journey, Emily discovered that appreciation was not limited to grand gestures but could be woven into the fabric of everyday life. It had the power to uplift spirits, forge deeper connections, and cultivate a sense of belonging.</p><p>of life, celebrating the small moments and spreading joy wherever we go.</p>',
                'readtime' => '2 Minute 20 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '5',
                'slug' => 'The-Tapestry-of-Life-Embracing-the-Journey-u-admin',
                'title' => 'The Tapestry of Life: Embracing the Journey',
                'body' => '<p>Life, like a vast tapestry, weaves a beautiful and intricate pattern of experiences, challenges, and moments of profound joy. In this captivating story, we follow the journey of Sarah, a young woman navigating the twists and turns of her own life.</p><p>Sarah\'s journey began with the innocence of childhood, where the world seemed full of endless possibilities. As she grew older, she encountered setbacks and hurdles that tested her resilience. But with each obstacle, Sarah discovered newfound strength and wisdom that propelled her forward.</p><p>Along her path, Sarah encountered a diverse cast of characters who played pivotal roles in shaping her journey. There was Mr. Johnson, a wise mentor who imparted invaluable life lessons about perseverance and self-belief. There was Lily, a kindred spirit who shared the highs and lows of friendship, reminding Sarah of the importance of connection and support.</p><p>As Sarah traversed the terrain of adulthood, she faced pivotal choices and crossroads. Some paths led to success and fulfillment, while others held valuable lessons in disguise. Through the highs and lows, she learned to embrace the uncertainty and trust in the process of her own growth.</p><p>sense of connection to something greater than herself.</p><p>As Sarah\'s story unfolded, she realized that life was not merely about reaching a destination but rather embracing the journey itself. The tapestry of her experiences, both triumphs and tribulations, formed the rich fabric of her existence. She embraced the beauty of imperfection and learned to find joy in the smallest of moments.</p><p>Through her journey of life, Sarah discovered the profound truth that the destination is ever-evolving, but the growth, lessons, and connections formed along the way are what truly matter. With newfound wisdom and a heart filled with gratitude, she embraced the uncertainty and embraced the tapestry of life that lay before her.</p><p>"The Tapestry of Life: Embracing the Journey" is a captivating tale that reminds us to embrace every twist and turn, every joy and challenge, as integral parts of our own unique journey. It encourages us to savor the present moment, cherish the connections we make, and find meaning in the ever-unfolding tapestry of life.</p>',
                'readtime' => '2 Minute 16 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '6',
                'slug' => 'Rising-from-the-Ashes-A-Journey-of-Recovery-u-admin',
                'title' => 'Rising from the Ashes: A Journey of Recovery',
                'body' => '<p>In the depths of despair and adversity, the human spirit has an extraordinary capacity for resilience and recovery. This inspiring story follows the path of Michael, a courageous individual who embarked on a profound journey of recovery.</p><p>Michael\'s life had been marred by addiction, leading him down a dark and destructive path. But deep within him, a flicker of hope remained, urging him to seek a better life. With unwavering determination, he took the first step towards recovery.</p><p>The road to recovery was not easy for Michael. It required him to confront his inner demons, face his past traumas, and make difficult choices to break free from the grips of addiction. He sought professional help, surrounded himself with a supportive network, and committed himself to a process of healing and transformation.</p><p>Throughout his journey, Michael discovered the power of self-reflection and self-compassion. He learned to embrace vulnerability, allowing himself to heal from the wounds of his past. He discovered inner strengths he never knew he possessed and found solace in the embrace of a recovery community that understood his struggles.</p><p>purpose.</p><p>Along the way, Michael learned valuable life lessons about forgiveness, acceptance, and the importance of self-care. He repaired broken relationships, rebuilt his self-esteem, and embraced a newfound sense of purpose. Through his experience, he became a beacon of hope for others who were on their own journey of recovery.</p><p>heal and create a brighter future.</p><p>Note: The story of recovery is deeply personal and can vary widely for each individual. It is important to approach the topic with sensitivity and respect for the unique experiences and challenges faced by those on their journey to recovery.</p>',
                'readtime' => '2 Minute 13 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '7',
                'slug' => 'Unleashing-Greatness-A-Journey-to-Success-u-admin',
                'title' => 'Unleashing Greatness: A Journey to Success',
                'body' => '<p>Success is not merely the achievement of external milestones, but a profound inner transformation that propels individuals to reach their fullest potential. In this captivating story, we follow the remarkable journey of Alex, a determined individual who pursued his dreams and embarked on a path to success.</p><p>Alex\'s story began with a burning passion and a vision that seemed beyond reach. He harbored grand aspirations and an unwavering belief in his abilities, despite facing numerous obstacles along the way. With relentless determination, he set out to turn his dreams into reality.</p><p>Throughout his journey, Alex encountered setbacks, failures, and moments of self-doubt. But he refused to let adversity define him. He embraced challenges as opportunities for growth, learning valuable lessons with each stumble. Through persistence and resilience, he found the strength to rise again, stronger and wiser.</p><p>As Alex pursued his goals, he surrounded himself with mentors and like-minded individuals who inspired and pushed him to reach new heights. He sought out knowledge, honed his skills, and embraced a mindset of continuous learning. With each step forward, he expanded his horizons and discovered new dimensions of success.</p><p>But success, for Alex, was not merely measured by external achievements. He realized that true success encompassed personal fulfillment, a sense of purpose, and the positive impact he could make on the lives of others. He strived to create a harmonious balance between professional accomplishments and the well-being of those around him.</p><p>As Alex\'s journey unfolded, he celebrated victories both big and small. He celebrated not only his own successes but also the achievements of his peers and collaborators. He recognized the power of collaboration and the importance of lifting others up on their own paths to success.</p><p>"Unleashing Greatness: A Journey to Success" is a captivating tale that reminds us that success is a multifaceted journey. It is a testament to the power of perseverance, self-belief, and the relentless pursuit of one\'s passions. Through Alex\'s story, we are inspired to embrace our own dreams, overcome obstacles with resilience, and unlock our full potential. It serves as a reminder that success is not a destination but an ongoing journey of growth, self-discovery, and the pursuit of excellence.</p>',
                'readtime' => '1 Minute 59 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '8',
                'slug' => 'The-Ripple-of-Kindness-Illuminating-Lives-u-admin',
                'title' => 'The Ripple of Kindness: Illuminating Lives',
                'body' => '<p>Kindness has the remarkable power to transform lives, uplift spirits, and create a ripple effect of positivity. In this heartwarming story, we delve into the extraordinary acts of kindness that shaped the lives of individuals and brought a community closer together.</p><p>Our story begins with Anna, a compassionate soul who believed in the inherent goodness of humanity. Anna\'s small acts of kindness, whether it was offering a helping hand to a stranger or lending an empathetic ear to a friend in need, had a profound impact on those around her.</p><p>One day, Anna\'s kindness caught the attention of Mark, a skeptical and disillusioned individual who had lost faith in the power of compassion. Intrigued by Anna\'s unwavering kindness, Mark decided to embark on a personal journey to understand its true significance.</p><p>As Mark observed and interacted with those touched by Anna\'s kindness, he witnessed the transformative power it had on their lives. A simple act of kindness, such as a smile, a kind word, or a supportive gesture, had the ability to brighten someone\'s day and restore hope in their hearts.</p><p>Inspired by Anna\'s example, Mark set out to spread kindness in his own unique way. He organized community projects, initiated random acts of kindness, and encouraged others to join him on this mission of creating a kinder world. The impact of their collective efforts rippled through the community, inspiring more individuals to embrace kindness as a way of life.</p><p>Through the experiences of various characters, we witness the far-reaching effects of kindness. From the homeless person who receives a warm meal and a listening ear, to the child who feels seen and valued through a simple act of kindness, each encounter has the potential to ignite a chain reaction of compassion and empathy.</p><p>reminded that even the smallest gestures can create a profound impact and bring light to the darkest corners of our world.</p><p>As we journey alongside Anna, Mark, and the community they touch, we are inspired to embrace kindness as a transformative force, fostering connections, healing wounds, and creating a more compassionate and harmonious society.</p>',
                'readtime' => '2 Minute 15 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '9',
                'slug' => 'Unleashing-the-Spirit-Within-A-Journey-of-Inner-Awakening-u-admin',
                'title' => 'Unleashing the Spirit Within: A Journey of Inner Awakening',
                'body' => '<p>The human spirit is a boundless wellspring of strength, resilience, and infinite potential. In this captivating story, we embark on a transformative journey of self-discovery and the unearthing of the indomitable spirit that resides within us all.</p><p>Our tale begins with Maya, a young woman who finds herself feeling disconnected and unfulfilled despite external success. Sensing a deeper longing within her soul, Maya embarks on a quest to rediscover her true essence and unleash the dormant spirit within.</p><p>Guided by an inner calling, Maya immerses herself in various spiritual practices, from meditation and mindfulness to exploring ancient wisdom and mystical teachings. With each step along her journey, Maya sheds layers of societal conditioning and taps into the boundless reservoir of her spirit.</p><p>Through moments of solitude and introspection, Maya unravels the profound truths that lie hidden within her being. She discovers that the spirit is not confined by the boundaries of the physical world but transcends into realms of intuition, creativity, and interconnectedness with all of existence.</p><p>As Maya\'s inner spirit awakens, she undergoes a profound transformation. She cultivates a deep sense of gratitude for life\'s blessings, embraces vulnerability as a gateway to authenticity, and learns to navigate challenges with courage and resilience. Her spirit becomes a guiding compass, illuminating the path towards personal growth and purpose.</p><p>Along her journey, Maya encounters fellow seekers who have embarked on their own paths of spiritual awakening. Through their shared experiences and collective wisdom, they form a supportive community that uplifts and inspires one another to live from a place of authenticity and alignment with their higher selves.</p><p>"Unleashing the Spirit Within: A Journey of Inner Awakening" is a captivating narrative that invites readers to embark on their own quest of self-discovery and spiritual awakening. It serves as a reminder that beyond the confines of our everyday existence lies a vast and limitless realm of the spirit, waiting to be explored and embraced.</p><p>Through Maya\'s story, we are reminded of our inherent connection to something greater, the power of self-reflection, and the transformative potential that lies within each of us. It encourages us to nurture our spirits, listen to the whispers of our souls, and embark on a lifelong journey of self-discovery, growth, and the realization of our highest potential.</p>',
                'readtime' => '2 Minute 4 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
            [
                'user_id' => '1',
                'tag_id' => '10',
                'slug' => 'Igniting-the-Flame-Within-Empowerment-Unleashed-u-admin',
                'title' => 'Igniting the Flame Within: Empowerment Unleashed',
                'body' => '<p>Empowerment is the catalyst that fuels personal growth, fosters resilience, and propels individuals to overcome challenges. In this empowering story, we dive into the transformative journey of Emma, a tenacious individual who embarks on a path of self-discovery and empowerment.</p><p>Emma\'s story begins with a sense of disempowerment, feeling trapped in a life that doesn\'t align with her true aspirations. Determined to break free from limitations, she embarks on a quest to reclaim her power and create a life of purpose and fulfillment.</p><p>Through a series of transformative experiences and encounters, Emma uncovers her inner strength and taps into her unique gifts and talents. She embraces self-belief and sheds the limiting beliefs that had held her back. With each step forward, she becomes more empowered, embracing her authentic self and fearlessly pursuing her dreams.</p><p>Along her journey, Emma encounters mentors, friends, and communities that uplift and support her growth. These empowering connections provide guidance, encouragement, and a sense of belonging. They remind her that she is not alone on her path and that together, they can create a ripple of positive change in the world.</p><p>As Emma\'s empowerment deepens, she becomes a beacon of inspiration for others. She shares her story, mentors aspiring individuals, and advocates for equality and empowerment on a broader scale. Through her actions, she ignites a spark within others, empowering them to step into their own greatness.</p><p>"Igniting the Flame Within: Empowerment Unleashed" is a compelling narrative that celebrates the transformative power of empowerment. It encourages readers to recognize their own potential, embrace their unique gifts, and navigate life\'s challenges with resilience and determination.</p><p>Through Emma\'s journey, we witness the profound impact that empowerment has on individuals and communities. It reminds us that we all possess the power to create positive change, both within ourselves and in the world around us. It invites readers to embark on their own journey of self-discovery, self-empowerment, and the pursuit of a purpose-driven life.</p><p>As we accompany Emma on her transformative quest, we are inspired to embrace our own power, uplift others, and create a world where empowerment becomes a driving force for personal growth, societal progress, and the fulfillment of our collective potential.</p>',
                'readtime' => '1 Minute 59 Seconds',
                'created_at' => now(),
                'updated_at' => now()
            ],
        ]);
    }
}
